### ISSUE TITLE
Add licence please

### ISSUE THREAD

**Issue by gitkundan** [SBentley/qvd-utils#1]
Looks very good Sam. To use this library will be good if you can insert a licence file so that users know how to distribute the code

**Comment by SBentley** [comment]
Hi @gitkundan , I have added a license now. Thanks for the suggestion.

**Comment by gitkundan** [comment]
Thanks @SBentley . Can you also please release it with licence file to PYPI. This will enable organizations to import from PYPI

**Comment by SBentley** [comment]
On there now, thanks.
![image](https://user-images.githubusercontent.com/5394952/118400802-17a68400-b65b-11eb-85dd-713d8d0d0b8d.png)
