### ISSUE TITLE
Update pandas requirement

### ISSUE THREAD

**Issue by FredStober** [SBentley/qvd-utils#15]
Would it be possible to loosen the constraint of "pandas~=1.1.4", so pip can resolve the packages even with newer pandas versions?
In my case I would require pandas 1.3.2 that comes with AWS Glue 3.0.

**Comment by Pendragon** [comment]
Same need for me. This version 1.1.4 of pandas is now outdated

**Comment by Phil-T1** [comment]
Same for me please, I like to stay current with Pandas. 1.1.4 is quite old.

**Comment by SBentley** [comment]
Hi all, I have relaxed the constraint to >= 1.1.4. Installing version 0.0.14 of this library should now work with the latest pandas versions.

**Comment by Phil-T1** [comment]
Hi, thanks! That's hugely appreciated.

**Comment by FredStober** [comment]
Thank you very much!
