### ISSUE TITLE
ValueError: arrays must all be same length

### ISSUE THREAD

**Issue by nath24** [SBentley/qvd-utils#7]
Hi,

I get this error when I try to read qvd file:

ValueError: arrays must all be same length

Thanks

**Comment by MvdCoer** [comment]
Hi,

Also getting this error:
ValueError: arrays must all be same length

But not with all files. Some smaller ones do work.

Thanks

**Comment by SBentley** [comment]
@MvdCoer @nath24 Thanks both for reporting, this issue should now be fixed. Make sure to update to version 0.0.10 to get the latest changes. Let me know if you still have any issues.

**Comment by MvdCoer** [comment]
@SBentley Thank you very much for solving this problem. It works great now.
